### ISSUE TITLE
Failing to build libmill (gcc, dns/dns.h)

### ISSUE THREAD

**Issue by rezad1393** [Intika-Linux-Proxy/SNI-SSL-Proxy#4]
make libmill.la
  CC       libmill_la-ip.lo
In file included from ip.c:44:
ip.c: In function ‘mill_ipremote_’:
dns/dns.h:1009:24: error: lvalue required as unary ‘&’ operand
 1009 | #define dns_opts(...) (&dns_quietinit((struct dns_options)DNS_OPTS_INIT(__VA_ARGS__)))
      |                        ^
ip.c:268:31: note: in expansion of macro ‘dns_opts’
  268 |         mill_dns_hints, NULL, dns_opts(), &rc);
      |                               ^~~~~~~~
make: *** [Makefile:1236: libmill_la-ip.lo] Error 1

https://github.com/sustrik/libdill/issues/191

how do you even use this if you cant compile it?

**Comment by intika** [comment]
Just tried with master release and it's working, i guess this error depend on your system and the different version you are using (gcc) you can try to use an other version of gcc (downgrade...). 
Also have a look at https://github.com/sustrik/libdill/issues/191#issuecomment-512795249 apparently this have been fixed on that PR. 

Let me know if you need further assistance

**Comment by intika** [comment]
Just tried with master release and it's working, i guess this error depend on your system and the 
 version of gcc that you are using, you can try to use an other version of gcc (v5.5 is working...). 

Also have a look at https://github.com/sustrik/libdill/issues/191#issuecomment-512795249 apparently this have been fixed on that PR.
